# Generated by Django 4.2.7 on 2024-03-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('color', models.CharField(blank=True, max_length=127, null=True)),
                ('price', models.PositiveIntegerField(max_length=64)),
                ('amount', models.PositiveIntegerField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
